version: '3'

services:
  runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes:
      - config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - ./register.sh:/register.sh:ro
      - ./run.sh:/run.sh:ro
    entrypoint: 
      - /usr/bin/dumb-init
      - --
    command: 
      - bash
      - -c
      - /register.sh && /run.sh
    env_file:
      - .env

volumes:
  config:
